Add typescript bindings
7upcat/mobx-event-bus pull request #3
Opened 2018-05-14 14:40 UTC by kibertoad

refs #2

2018-05-15 17:42 UTC, povilas-jurjevas-ht requested changes

2018-05-15 17:42 UTC, povilas-jurjevas-ht commented on lib/index.d.ts
> +/* Type definitions for mobx-event-bus */
This file shouldn't be placed under `lib`, but rather the root directory of the package. If you want it to live in some other directory, that should be explicitly specified in `package.json` using the "types" property (more info [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)).

2018-05-15 17:47 UTC, povilas-jurjevas-ht commented on lib/index.d.ts
> +export function subscribe<Event>(topic: string, selector?: Selector<Event>)
Would it make more sense to define an `Event` type with `topic` and `payload` properties and then request only the Event's payload type using this generic? This seems to be the API as described in [API docs](https://github.com/7upcat/mobx-event-bus#api-documents) of this project.

2018-05-21 00:10 UTC, 7upcat approved these changes

2018-05-21 00:11 UTC, 7upcat commented
Great work  ： ）

2018-05-21 00:12 UTC, merged